# Source: https://id.wikipedia.org/wiki/Daftar_kecamatan_dan_kelurahan_di_Jabodetabek
LOCATIONS = {
  # Jakarta Pusat
  'jakarta-pusat': [
    'cempaka-putih',
    'gambir',
    'johar-baru',
    'kemayoran',
    'menteng',
    'sawah-besar',
    'senen',
    'tanah-abang',
  ],
  # Jakarta Utara
  'jakarta-utara': [
    'cilincing',
    'kelapa-gading',
    'koja',
    'pademangan',
    'penjaringan',
    'tanjung-priok',
  ],
  # Jakarta Timur
  'jakarta-timur': [
    'cakung',
    'cipayung',
    'ciracas',
    'duren-sawit',
    'jatinegara',
    'kramat-jati',
    'makasar',
    'matraman',
    'pasar-rebo',
    'pulo-gadung',
  ],
  # JAkarata Selatan
  'jakarta-selatan': [
    'cilandak',
    'jagakarsa',
    'kebayoran-baru',
    'kebayoran-lama',
    'mampang-prapatan',
    'pancoran',
    'pasar-minggu',
    'pesanggrahan',
    'setiabudi',
    'tebet',
  ],
  # Jakarta Barat
  'jakarta-barat': [
    'cengkareng',
    'grogol-petamburan',
    'tamansari',
    'tambora',
    'kebon-jeruk',
    'kalideres',
    'palmerah',
    'kembangan',
  ],
  # Kepulaun Seribu
  'kepulauan-seribu': [
    'kepulauan-seribu-utara',
    'kepulauan-seribu-selatan',
  ],
  # Bogor
  'bogor': [
    # Kota Bogor
    'bogor-barat',
    'bogor-selatan',
    'bogor-tengah',
    'bogor-timur',
    'bogor-utara',
    'tanah-sareal',
    # Kabupaten Bogor
    'babakan-madang',
    'bojonggede',
    'caringin',
    'cariu',
    'ciampea',
    'ciawi',
    'cibinong',
    'cibungbulang',
    'cigombong',
    'cigudeg',
    'cijeruk',
    'cileungsi',
    'ciomas',
    'cisarua',
    'ciseeng',
    'citeureup',
    'dramaga',
    'gunung-putri',
    'gunung-sindur',
    'jasinga',
    'jonggol',
    'kemang',
    'klapanunggal',
    'leuwiliang',
    'leuwisadeng',
    'megamendung',
    'nanggung',
    'parung',
    'parung-panjang',
    'ranca-bungur',
    'rumpin',
    'sukajaya',
    'sukamakmur',
    'sukaraja',
    'tajur-halang',
    'tamansari',
    'tanjungsari',
    'tenjo',
    'tenjolaya',
  ],
  # Depok
  'depok': [
    # Kota Depok
    'beji',
    'bojong-sari',
    'cilodong',
    'cimanggis',
    'cinere',
    'cipayung',
    'limo',
    'pancoran-mas',
    'sawangan',
    'sukmajaya',
    'tapos',
  ],
  # Tangerang
  'tangerang': [
    # Kota Tangerang
    'batuceper',
    'benda',
    'cibodas',
    'ciledug',
    'cipondoh',
    'jati-uwung',
    'karang-tengah',
    'karawaci',
    'larangan',
    'neglasari',
    'periuk',
    'pinang',
    'tangerang',
    # Kabupaten Tangerang
    'balaraja',
    'cikupa',
    'cisauk',
    'cisoka',
    'curug',
    'gunung-kaler',
    'jambe',
    'jayanti',
    'kelapa-dua',
    'kemiri',
    'kresek',
    'kronjo',
    'kosambi',
    'legok',
    'mauk',
    'mekar-baru',
    'pagedangan',
    'pakuhaji',
    'panongan',
    'pasar-kemis',
    'rajeg',
    'sepatan',
    'sepatan-timur',
    'sindang-jaya',
    'solear',
    'sukadiri',
    'sukamulya',
    'teluknaga',
    'tigaraksa',
  ],
  # Tangerang Selatan
  'tangerang-selatan': [
    # Kota Tangerang Selatan
    'ciputat',
    'ciputat-timur',
    'pamulang',
    'pondok-aren',
    'serpong',
    'serpong-utara',
    'setu',
  ],
  # Bekasi
  'bekasi': [
    # Kota Bekasi
    'bantar-gebang',
    'bekasi-barat',
    'bekasi-selatan',
    'bekasi-timur',
    'bekasi-utara',
    'jati-asih',
    'jatisampurna',
    'medan-satria',
    'mustikajaya',
    'pondok-gede',
    'pondokmelati',
    'rawalumbu',
    # Kabupaten Bekasi
    'babelan',
    'bojongmangu',
    'cabangbungin',
    'cibarusah',
    'cibitung',
    'cikarang-barat',
    'cikarang-pusat',
    'cikarang-selatan',
    'cikarang-timur',
    'cikarang-utara',
    'karangbahagia',
    'kedungwaringin',
    'muara-gembong',
    'pebayuran',
    'serang-baru',
    'setu',
    'sukakarya',
    'sukatani',
    'sukawangi',
    'tambelang',
    'tambun-selatan',
    'tambun-utara',
    'tarumajaya',
  ],
  # Cianjur
  'cianjur': [
    'agrabinta',
    'bojongpicung',
    'campaka',
    'campaka-mulya',
    'cianjur',
    'cibeber',
    'cibinong',
    'cidaun',
    'cijati',
    'cikadu',
    'cikalongkulon',
    'cilaku',
    'cipanas',
    'ciranjang',
    'cugenang',
    'gekbrong',
    'haurwangi',
    'kadupandak',
    'karangtengah',
    'leles',
    'mande',
    'naringgul',
    'pacet',
    'pagelaran',
    'sindangbarang',
    'sukaluyu',
    'sukanagara',
    'sukaresmi',
    'takokak',
    'tanggeung',
    'warungkondang',
  ],
}